# Generated by Django 3.2.8 on 2021-12-05 01:39

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('S', 'Select Equipment'), ('UPS', 'UPS'), ('UB', 'UPS Battery'), ('PI', 'Power Inverter'), ('PIB', 'Power Inverter Battery'), ('SP', 'Surge Protector'), ('PG', 'Power Generator'), ('GE', 'General Electrical Wiring and Earthing Condition'), ('GTO', 'General Technical Observation'), ('BTR', 'Battery Rack Type'), ('AS', 'AVS Switcher'), ('OT', 'Others')], default='S', max_length=4)),
                ('equipment_others', models.CharField(blank=True, max_length=120, null=True)),
                ('brand_name', models.CharField(max_length=150)),
                ('technical_specification', models.CharField(max_length=120)),
                ('date_manufactured', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('replacement_date', models.DateField()),
                ('contact_person', models.CharField(max_length=150)),
                ('equipment_status', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], default='Good', max_length=1)),
                ('remark', models.CharField(max_length=150)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(choices=[('S', '-----------'), ('AB', 'Abia'), ('FCT', ' Abuja'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara')], default='S', max_length=4)),
                ('address', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
