# Generated by Django 3.2.8 on 2021-12-11 22:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('S', 'Select Equipment'), ('UPS', 'UPS'), ('UB', 'UPS Battery'), ('PI', 'Power Inverter'), ('IB', 'Inverter Battery'), ('SP', 'Surge Protector'), ('PG', 'Power Generator'), ('VR', 'Voltage Regulator'), ('BS', 'Bypass Switch'), ('SOP', 'Solar Panel'), ('OT', 'Others')], default='S', max_length=4)),
                ('equipment_others', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('life_span', models.CharField(choices=[('NR', 'Not Rated'), ('1L', '1-2 Years'), ('2L', '2-3 Years'), ('3L', '3-4 Years'), ('4L', '4-5 Years'), ('5L', '5-6 Years'), ('6L', '6-7 Years'), ('7L', '7-8 Years'), ('8L', '8-9 Years'), ('9L', '9-10 Years'), ('2kL', '2-4 Years'), ('4kL', '4-6 Years'), ('6kL', '6-8 Years'), ('8kL', '8-10 Years'), ('2YL', '20-25 Years'), ('5YL', '25-30 Years'), ('10YL', '30-35 Years'), ('OT', 'Others')], default='NR', max_length=5)),
                ('brand_name', models.CharField(choices=[('', '---------------- Battery Brands----------------'), ('AMARON', 'AMARON'), ('ARCCHAR', 'ARCCHAR'), ('DAYSTAR', 'DAYSTAR'), ('E.P', 'E.P'), ('EVER EXCEED', 'EVER EXCEED'), ('FELICITY', 'FELICITY'), ('G.P', 'G.P'), ('GASTON', 'GASTON'), ('GENUS', 'GENUS'), ('HOPPECKE', 'HOPPECKE'), ('MECURY', 'MECURY'), ('MF', 'MF'), ('MONBAT', 'MONBAT'), ('MVR', 'MVR'), ('POWER PREM', 'POWER PREM'), ('POWER STAR', 'POWER STAR'), ('POWER V', 'POWER V'), ('PRIME SOLAR', 'PRIME SOLAR'), ('PROSTAR-LEMAX', 'PROSTAR-LEMAX'), ('QUANTA', 'QUANTA'), ('RITAR', 'RITAR'), ('SHOTO', 'SHOTO'), ('SURFIT', 'SURFIT'), ('TRATA', 'TRATA'), ('TROJAN SAGEM', 'TROJAN SAGEM'), ('TROJAN(SLIM)', 'TROJAN(SLIM)'), (' ', '---------------- Generator Brands ----------------'), ('C-POWER', 'C-POWER'), ('CUMMINS', 'CUMMINS'), ('FG WILSON', 'FG WILSON'), ('GHADDOR', 'GHADDOR'), ('HAT GLOBAL SP', 'HAT GLOBAL SP'), ('JMG', 'JMG'), ('JOHN HOLT', 'JOHN HOLT'), ('JUBALLI', 'JUBALLI'), ('KHNEISSER HIJAZI', 'KHNEISSER HIJAZI'), ('MANTRAC', 'MANTRAC'), ('MARAPCO', 'MARAPCO'), ('MIKANO', 'MIKANO'), ('PERKINS', 'PERKINS'), (' ', '---------------- Inverter Brands ----------------'), ('AARCHOR', 'AARCHOR'), ('BPC', 'BPC'), ('COMP HC', 'COMP HC'), ('EMERSON', 'EMERSON'), ('ENDLESS POWER', 'ENDLESS POWER'), ('ENERGIER', 'ENERGIER'), ('FELICITY', 'FELICITY'), ('FRONIOUS', 'FRONIOUS'), ('GENNEX', 'GENNEX'), ('INFORM', 'INFORM'), ('IPOWER PLUS', 'IPOWER PLUS'), ('KINERGIER PRO', 'KINERGIER PRO'), ('LIEBERT', 'LIEBERT'), ('MEGATECH', 'MEGATECH'), ('MONEY POWER', 'MONEY POWER'), ('MST SERIES', 'MST SERIES'), ('NUMERIC', 'NUMERIC'), ('OPTI-SOLAR', 'OPTI-SOLAR'), ('POWER PRO', 'POWER PRO'), ('POWERGEM PRO', 'POWERGEM PRO'), ('POWERSINE', 'POWERSINE'), ('PROSTAR', 'PROSTAR'), ('SCHNEIDER', 'SCHNEIDER'), ('SOROTEC', 'SOROTEC'), ('OT', 'Others')], max_length=90)),
                ('brand_others', models.CharField(blank=True, max_length=120, null=True)),
                ('technical_specification', models.CharField(max_length=120)),
                ('date_manufactured', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('replacement_date', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('equipment_status', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], default='Good', max_length=1)),
                ('remark', models.CharField(max_length=150)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.installation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=15, null=True)),
                ('cug_num1', models.CharField(blank=True, max_length=14, null=True)),
                ('cug_num2', models.CharField(blank=True, max_length=14, null=True)),
                ('state', models.CharField(choices=[('S', '-----------'), ('AB', 'Abia'), ('FCT', ' FCT'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara')], default='S', max_length=4)),
                ('address', models.CharField(max_length=200)),
                ('regional_office', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('S', '-----------'), ('ABJ1', 'ABUJA 1'), ('ABJ2', 'ABUJA 2'), ('AI', 'AGEGE IKORODU'), ('AP', 'APAPA'), ('AW', 'AWKA'), ('CRA', 'CROSS RIVER AKWA IBOM'), ('EE', 'ENUGU EBONYI'), ('FE', 'FESTAC'), ('IK', 'IKEJA'), ('IKL', 'IKOYI'), ('IA', 'IMO ABIA'), ('LI', 'LAGOS ISLAND'), ('MA1', 'MAINLAIN 1'), ('MA2', 'MAINLAIN 2'), ('MD1', 'MIDWEST 1'), ('MD2', 'MIDWEST 2'), ('NC', 'NORTH CENTRAL'), ('NE', 'NORTH EAST'), ('NW1', 'NORTH WEST 1'), ('NW2', 'NORTH WEST 2'), ('ON', 'ONITSHA'), ('RB1', 'RIVER BAYELSA 1'), ('RB2', 'RIVER BAYELSA 2'), ('SW1', 'SOUTH WEST 1'), ('SW2', 'SOUTH WEST 2'), ('VI', 'VICTORIA ISLAND')], default='S', max_length=5)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.location'),
        ),
    ]
