# Generated by Django 3.2.8 on 2021-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='brand_name',
            field=models.CharField(choices=[('S', 'Select Brand'), ('', '---------------- Battery Brands----------------'), ('AMARON', 'AMARON'), ('ARCCHAR', 'ARCCHAR'), ('DAYSTAR', 'DAYSTAR'), ('E.P', 'E.P'), ('EVER EXCEED', 'EVER EXCEED'), ('FELICITY', 'FELICITY'), ('G.P', 'G.P'), ('GASTON', 'GASTON'), ('GENUS', 'GENUS'), ('HOPPECKE', 'HOPPECKE'), ('MECURY', 'MECURY'), ('MF', 'MF'), ('MONBAT', 'MONBAT'), ('MVR', 'MVR'), ('POWER PREM', 'POWER PREM'), ('POWER STAR', 'POWER STAR'), ('POWER V', 'POWER V'), ('PRIME SOLAR', 'PRIME SOLAR'), ('PROSTAR-LEMAX', 'PROSTAR-LEMAX'), ('QUANTA', 'QUANTA'), ('RITAR', 'RITAR'), ('SHOTO', 'SHOTO'), ('SURFIT', 'SURFIT'), ('TRATA', 'TRATA'), ('TROJAN SAGEM', 'TROJAN SAGEM'), ('TROJAN(SLIM)', 'TROJAN(SLIM)'), (' ', '---------------- Generator Brands ----------------'), ('C-POWER', 'C-POWER'), ('CUMMINS', 'CUMMINS'), ('FG WILSON', 'FG WILSON'), ('GHADDOR', 'GHADDOR'), ('HAT GLOBAL SP', 'HAT GLOBAL SP'), ('JMG', 'JMG'), ('JOHN HOLT', 'JOHN HOLT'), ('JUBALLI', 'JUBALLI'), ('KHNEISSER HIJAZI', 'KHNEISSER HIJAZI'), ('MANTRAC', 'MANTRAC'), ('MARAPCO', 'MARAPCO'), ('MARCOPOLO', 'MARCOPOLO'), ('MIKANO', 'MIKANO'), ('PERKINS', 'PERKINS'), (' ', '---------------- Inverter Brands ----------------'), ('AARCHOR', 'AARCHOR'), ('BPC', 'BPC'), ('COMP HC', 'COMP HC'), ('EMERSON', 'EMERSON'), ('ENDLESS POWER', 'ENDLESS POWER'), ('ENERGIER', 'ENERGIER'), ('FELICITY', 'FELICITY'), ('FRONIOUS', 'FRONIOUS'), ('GENNEX', 'GENNEX'), ('INFORM', 'INFORM'), ('IPOWER PLUS', 'IPOWER PLUS'), ('KINERGIER PRO', 'KINERGIER PRO'), ('LIEBERT', 'LIEBERT'), ('MEGATECH', 'MEGATECH'), ('MONEY POWER', 'MONEY POWER'), ('MST SERIES', 'MST SERIES'), ('NUMERIC', 'NUMERIC'), ('OPTI-SOLAR', 'OPTI-SOLAR'), ('POWER PRO', 'POWER PRO'), ('POWERGEM PRO', 'POWERGEM PRO'), ('POWERSINE', 'POWERSINE'), ('PROSTAR', 'PROSTAR'), ('SCHNEIDER', 'SCHNEIDER'), ('SOROTEC', 'SOROTEC'), ('OT', 'Others')], max_length=90),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
