# Generated by Django 3.2.8 on 2021-12-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.installation'),
        ),
        migrations.AddField(
            model_name='location',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.location'),
        ),
    ]
